const roles={
modpack:{icon:"🧩",name:"Modpack Maintainer",desc:"Keep the Beyond SMP modpack updated, tested and stable.",doing:["Monitor mod updates","Test new versions","Troubleshoot conflicts","Maintain the development instance","Prepare verified Modrinth releases"],looking:["Minecraft modpack experience","Familiarity with Fabric","Ability to troubleshoot problems","Reliability and attention to detail"],q:[["experience","What experience do you have maintaining Minecraft modpacks?"],["fabric","What experience do you have with Fabric?"],["troubleshoot","How would you approach a mod conflict or broken update?"]]},
moderator:{icon:"🛡️",name:"Moderator",desc:"Help manage the community and make Beyond SMP a great place to play.",doing:["Help keep the community welcoming","Handle rule issues fairly","Support players","Assist with events and server activity"],looking:["Good judgement","Clear communication","Reliability","Ability to stay calm during disagreements"],q:[["experience","Have you moderated a Minecraft or Discord community before?"],["scenario","How would you handle a disagreement between two players?"],["community","What makes a good SMP community?"]]},
developer:{icon:"🧑‍💻",name:"Developer",desc:"Help build the technology, websites and systems behind Beyond SMP.",doing:["Build and maintain website features","Develop server or community systems","Debug technical problems","Turn ideas into reliable features"],looking:["Programming or web-development experience","Problem-solving ability","Attention to detail","Willingness to learn"],q:[["experience","What programming or development experience do you have?"],["project","Tell us about a project you're proud of."],["debug","How do you normally approach debugging a problem?"]]},
builder:{icon:"🏗️",name:"Builder",desc:"Help create the world and environments of Beyond SMP.",doing:["Build locations and environments","Help shape faction areas","Work from references or plans","Collaborate with other builders"],looking:["Minecraft building experience","Creativity","Patience and attention to detail","Ability to follow a style or brief"],q:[["experience","What kind of Minecraft building have you done?"],["style","What building styles are you most comfortable with?"],["portfolio","Do you have builds or screenshots you could show the team?"]]}};let selected,step=1;
const rolesEl=document.querySelector("#roles");Object.entries(roles).forEach(([key,r])=>{const b=document.createElement("button");b.className="card";b.innerHTML=`<span class="icon">${r.icon}</span><h3>${r.name}</h3><p>${r.desc}</p><span class="apply">Apply →</span>`;b.onclick=()=>showRole(key);rolesEl.appendChild(b)});
const sections=["roles","role","form","done"],q=id=>document.querySelector(id),showOnly=id=>sections.forEach(s=>q("#"+s).classList.toggle("hidden",s!==id));
function showRole(key){selected=key;const r=roles[key];q("#rname").textContent=r.name;q("#rdesc").textContent=r.desc;q("#doing").innerHTML=r.doing.map(x=>`<li>${x}</li>`).join("");q("#looking").innerHTML=r.looking.map(x=>`<li>${x}</li>`).join("");showOnly("role");scrollTo(0,0)}
document.querySelectorAll(".back")[0].onclick=()=>showOnly("roles");document.querySelectorAll(".back")[1].onclick=()=>showOnly("role");
q("#start").onclick=()=>{step=1;const r=roles[selected];q("#steps").innerHTML=`<div class="step active" data-step="1"><label class="field">Minecraft username<input name="minecraft" required></label><label class="field">Discord username<input name="discord" required></label><label class="field">Age range<select name="age" required><option value="">Choose one</option><option>Under 13</option><option>13–15</option><option>16–17</option><option>18+</option></select></label><label class="field">Time zone<input name="timezone" required></label><label class="field">Availability / activity<textarea name="availability" required></textarea></label></div><div class="step" data-step="2"><p>Selected role:</p><h3>${r.icon} ${r.name}</h3></div><div class="step" data-step="3">${r.q.map(([n,t])=>`<label class="field">${t}<textarea name="${n}" required></textarea></label>`).join("")}</div><div class="step" data-step="4"><label class="field">Why do you want to join the Beyond SMP team?<textarea name="why" required></textarea></label><label class="field">Why should we choose you?<textarea name="choose" required></textarea></label><label class="field">Anything else you'd like us to know?<textarea name="anything"></textarea></label></div>`;render();showOnly("form");scrollTo(0,0)};
function render(){document.querySelectorAll(".step").forEach(x=>x.classList.toggle("active",+x.dataset.step===step));q("#label").textContent=`STEP ${step} OF 4`;q("#bar").style.width=step*25+"%";q("#prev").classList.toggle("hidden",step===1);q("#next").textContent=step===4?"Submit Application →":"Continue →"}
q("#prev").onclick=()=>{if(step>1){step--;render()}};q("#next").onclick=()=>{const active=document.querySelector(".step.active");if([...active.querySelectorAll("[required]")].some(x=>!x.value.trim())){active.querySelector("[required]:invalid")?.reportValidity();return}if(step<4){step++;render()}else{showOnly("done");scrollTo(0,0)}};